### ISSUE TITLE
Build process in AppVeyor 

### ISSUE THREAD

**Issue by daffers** [jchannon/WebAPI.Testing#7]
It would be good if the project was build in AppVeyor and automatically deployed to nuget. Its free and easy to setup.

**Comment by jchannon** [comment]
Given you write access to this repo. Feel free to add appveyor

**Comment by daffers** [comment]
Cool, I’d set it up to deploy direct to nuget, can you share the key with me you use to upload?

**Comment by jchannon** [comment]
I can make you a nuget  co-owner and you can use yours if thats ok

**Comment by daffers** [comment]
That’s perfect. My account name is dafydd.giddins

**Comment by jchannon** [comment]
all done!
